### ISSUE TITLE
Implement queue tracking

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#236]
We have the data and code to implement queue tracking. This allows us to track how long a request or background job has waited in the queue before being processed. This is currently implemented in the Ruby gem for almost all HTTP request and background jobs.

## TODO

- [x] Implement `_set_queue_start` in NIF
- [x] Implement `set_queue_start` in transaction
- [ ] Implement queue tracking in plug (and Phoenix)
- [ ] Test on a production server/service (such as Heroku (we track the Heroku specific header, see PR #235)
- [ ] Documentation. (Does this require documentation? I don't see it for the Ruby gem)
