### ISSUE TITLE
Log to stdout and log level debug crash app on 1.6.6+

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#383]
Reproducible on 1.6.6 and higher. Doesn't occur on 1.6.5 and lower.
Platform: confirmed on macOS.
Framework: confirmed with Phoenix.

```
$ mix phx.server
# stuff
[2018-07-16T11:16:29 (extension) #17638][Error] appsignal: Panic encountered in 'appsignal_start', stopping appsignal extension: failed printing to stdout: Resource temporarily unavailable (os error 35)
```

## Config

```elixir
config :appsignal, :config,
  active: true,
  env: Mix.env,
  debug: true,
  log: "stdout",
  name: :appsignal_phoenix_example,
  push_api_key: "00000000-0000-0000-0000-000000000000"
```

## TODO

- [ ] Find out if it's isolated to Elixir or if it also occurs in the Ruby gem.
- [ ] Find out if it's isolated to macOS.
- [ ] Find out the cause.
- [ ] Fix the problem.

**Comment by jeffkreeftmeijer** [comment]
We haven’t been able to reproduce this since, so I’m closing this for now. Please reopen if this is still an issue.
