### ISSUE TITLE
Support mirrors for extension download

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#508]
Ruby counterpart: https://github.com/appsignal/appsignal-ruby/pull/558
Agent PR for Ruby change: https://github.com/appsignal/appsignal-agent/pull/467

## TODO

- [x] Update Agent ship task to use new agent.exs format (based on agent.yml file) - https://github.com/appsignal/appsignal-agent/pull/714
- [x] Add new agent.exs file with new format to this project
- [x] Update mix_helpers.exs logic to read from new format

**Comment by jvanbaarsen** [comment]
Requested here: [internal link](https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/unassigned/conversations/24625042214)

**Comment by tombruijn** [comment]
Added agent changes in https://github.com/appsignal/appsignal-agent/pull/714
