### ISSUE TITLE
Fix references to `debug` config option

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#746]
There are some references remaining to the `debug` option that has been replaced with the `log_level` config option.

See what parts need to be updated to use `log_level` and what parts can be removed now.

This doesn't mean remove the `debug` and `transaction_debug_mode` options entirely. They're deprecated and should remain in the package, but they should not be the primary source of behavior.

## TODO

- [ ] https://github.com/appsignal/appsignal-elixir/blob/c0a98928fb331436f01b7b41212decf7ab949ed1/lib/appsignal/config.ex#L127-L133
- [ ] https://github.com/appsignal/appsignal-elixir/blob/c0a98928fb331436f01b7b41212decf7ab949ed1/lib/appsignal/logger.ex#L7-L15
- [x] Look through the integration to find other places.

**Comment by unflxw** [comment]
I think there might be a problem here: the backwards compatibility logic for overriding the value of `log_level` based on `debug`/`transaction_debug_mode` lives in the agent, not in the integrations... and I think this is going to lead to somewhat inconsistent behaviour, unless we re-implement the `log_level` backwards compatibility in the integrations -- and then we have, potentially, four implementations of it.

Consider the following: suppose that the above snippets are updated to listen to the `log_level` config option instead of to the `debug` config option. If the user then sets the `debug` config option to `true`, the agent will (correctly) act as if `log_level` is `debug`, but these snippets in the extension itself will not. To address this, the snippets above would have to check for `log_level == "debug" || debug || transaction_debug_mode` -- effectively re-implementing the logic added to the agent in [appsignal-agent#730](https://github.com/appsignal/appsignal-agent/pull/730) in the integration side.

**Comment by tombruijn** [comment]
I don't think we can avoid reimplementing it in the integrations. We already have [one check for this in the Ruby gem](https://github.com/appsignal/appsignal-ruby/blob/ef2982fd7d1760f8062a20fa15a46131a0745cd2/lib/appsignal/config.rb#L262-L269) as well. But I think it will only need one of these checks for Ruby and Elixir in a "Config.debug" method/function.

At least we won't have to log the deprecation warning. That's done by the extension.

The Node.js integration doesn't do anything with the debug option, even though [we have a function available for it](https://github.com/appsignal/appsignal-nodejs/blob/3ce0e21e72a80c0a397aa28ee98ae4f33fa20250/packages/nodejs/src/config.ts#L48-L50). This function can be updated to use `log_level` without fallback, because it's never called.

Let's try and release new major releases for all integrations soon so we can remove all the deprecations! Even if they're just "clean up and maintenance" releases.
