### ISSUE TITLE
Add "override" config source

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-elixir#752]
As discussed in https://github.com/appsignal/integration-guide/pull/128, we want to track some config options in the "override" source. Such config options are `send_session_data` and the deprecated `skip_session_data`, after the changes in #749.

## TODO

- [x] Add "override" config source to the Config module
- [x] Move the backwards compatability logic to be set through the "override" source, rather than after the fact as is done now
    - Move the overrides that are now reported in the "system" to the "override" source
- [x] Update the diagnose report to report the "override" source
- [x] Update Elixir [load order docs page](https://docs.appsignal.com/elixir/configuration/load-order.html) to mention the "override" source - https://github.com/appsignal/appsignal-docs/pull/549
